# Generated by Django 5.2.17 on 2026-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
